### ISSUE TITLE
Mir Inlining

### ISSUE THREAD

**Issue by wesleywiser** [wesleywiser/rust#2]
Notes below

**Comment by wesleywiser** [comment]
## 11/11

Built bootstrap compiler from `775eab58835f9bc0f1f01ccbb79725dce0c73b51`
Build stage1 compiler from `775eab58835f9bc0f1f01ccbb79725dce0c73b51`.
 - `RUSTFLAGS=`

`run-pass` failures:

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/debuginfo-lto.rs
    [run-pass] run-pass/fat-lto.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/lto-many-codegen-units.rs
    [run-pass] run-pass/lto-still-runs-thread-dtors.rs
    [run-pass] run-pass/optimization-fuel-0.rs
    [run-pass] run-pass/optimization-fuel-1.rs
    [run-pass] run-pass/panic-runtime/lto-abort.rs
    [run-pass] run-pass/panic-runtime/lto-unwind.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
    [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs
    [run-pass] run-pass/stack-probes-lto.rs
    [run-pass] run-pass/ufcs-polymorphic-paths.rs
```

- `RUSTFLAGS="-Z fuel=rustc_mir=0"`

`run-pass` failures:

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/debuginfo-lto.rs
    [run-pass] run-pass/fat-lto.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/lto-many-codegen-units.rs
    [run-pass] run-pass/lto-still-runs-thread-dtors.rs
    [run-pass] run-pass/optimization-fuel-0.rs
    [run-pass] run-pass/optimization-fuel-1.rs
    [run-pass] run-pass/panic-runtime/lto-abort.rs
    [run-pass] run-pass/panic-runtime/lto-unwind.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
    [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs
    [run-pass] run-pass/stack-probes-lto.rs
    [run-pass] run-pass/ufcs-polymorphic-paths.rs
```

- `RUSTFLAGS="-Z fuel=rustc_llvm=0"`

`run-pass` failures:

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/debuginfo-lto.rs
    [run-pass] run-pass/fat-lto.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/lto-many-codegen-units.rs
    [run-pass] run-pass/lto-still-runs-thread-dtors.rs
    [run-pass] run-pass/optimization-fuel-0.rs
    [run-pass] run-pass/optimization-fuel-1.rs
    [run-pass] run-pass/panic-runtime/lto-abort.rs
    [run-pass] run-pass/panic-runtime/lto-unwind.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
    [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs
    [run-pass] run-pass/stack-probes-lto.rs
    [run-pass] run-pass/ufcs-polymorphic-paths.rs
```

**Comment by wesleywiser** [comment]
## 11/12

- `RUSTFLAGS="-Z fuel=rustc=0"` 

`run-pass` failures:

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/debuginfo-lto.rs
    [run-pass] run-pass/fat-lto.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/lto-many-codegen-units.rs
    [run-pass] run-pass/lto-still-runs-thread-dtors.rs
    [run-pass] run-pass/optimization-fuel-0.rs
    [run-pass] run-pass/optimization-fuel-1.rs
    [run-pass] run-pass/panic-runtime/lto-abort.rs
    [run-pass] run-pass/panic-runtime/lto-unwind.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
    [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs
    [run-pass] run-pass/stack-probes-lto.rs
    [run-pass] run-pass/ufcs-polymorphic-paths.rs
```

- `RUSTFLAGS="-Z fuel=std=0"`

`run-pass` failures:

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/debuginfo-lto.rs
    [run-pass] run-pass/fat-lto.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/lto-many-codegen-units.rs
    [run-pass] run-pass/lto-still-runs-thread-dtors.rs
    [run-pass] run-pass/optimization-fuel-0.rs
    [run-pass] run-pass/optimization-fuel-1.rs
    [run-pass] run-pass/panic-runtime/lto-abort.rs
    [run-pass] run-pass/panic-runtime/lto-unwind.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
    [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs
    [run-pass] run-pass/stack-probes-lto.rs
    [run-pass] run-pass/ufcs-polymorphic-paths.rs
```

- `RUSTFLAGS="-Z fuel=rustc_codegen_llvm=0"`

`run-pass` failures:

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/debuginfo-lto.rs
    [run-pass] run-pass/fat-lto.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/lto-many-codegen-units.rs
    [run-pass] run-pass/lto-still-runs-thread-dtors.rs
    [run-pass] run-pass/optimization-fuel-0.rs
    [run-pass] run-pass/optimization-fuel-1.rs
    [run-pass] run-pass/panic-runtime/lto-abort.rs
    [run-pass] run-pass/panic-runtime/lto-unwind.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
    [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs
    [run-pass] run-pass/stack-probes-lto.rs
    [run-pass] run-pass/ufcs-polymorphic-paths.rs
```

- `RUSTFLAGS="-Z fuel=rustc_driver=0"`

`run-pass` failures:

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/debuginfo-lto.rs
    [run-pass] run-pass/fat-lto.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/lto-many-codegen-units.rs
    [run-pass] run-pass/lto-still-runs-thread-dtors.rs
    [run-pass] run-pass/optimization-fuel-0.rs
    [run-pass] run-pass/optimization-fuel-1.rs
    [run-pass] run-pass/panic-runtime/lto-abort.rs
    [run-pass] run-pass/panic-runtime/lto-unwind.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
    [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs
    [run-pass] run-pass/stack-probes-lto.rs
    [run-pass] run-pass/ufcs-polymorphic-paths.rs
```

- `RUSTFLAGS="-Z fuel=rustc_typeck=0"` 

`rust-pass` failures:

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/debuginfo-lto.rs
    [run-pass] run-pass/fat-lto.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/lto-many-codegen-units.rs
    [run-pass] run-pass/lto-still-runs-thread-dtors.rs
    [run-pass] run-pass/optimization-fuel-0.rs
    [run-pass] run-pass/optimization-fuel-1.rs
    [run-pass] run-pass/panic-runtime/lto-abort.rs
    [run-pass] run-pass/panic-runtime/lto-unwind.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
    [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs
    [run-pass] run-pass/stack-probes-lto.rs
    [run-pass] run-pass/ufcs-polymorphic-paths.rs
```

**Comment by wesleywiser** [comment]
## 11/13

Started looking into the `run-pass/ufcs-polymorphicpaths.rs` test failure. 

Minimized repro:

```rust
trait Size: Sized {
    fn size() -> usize { 0 }
}
impl<T> Size for T {}

pub fn main() {
    static S: fn() -> usize = bool::size;
}
```

```
wesley@endurance:~/code/rust/test> RUST_BACKTRACE=1 rustc ufcs-polymorphic-paths.rs
warning: static item is never used: `S`
 --> ufcs-polymorphic-paths.rs:7:5
  |
7 |     static S: fn() -> usize = bool::size;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

error: internal compiler error: librustc_mir/const_eval.rs:663: static eval failure didn't emit an error: TooGeneric
 --> ufcs-polymorphic-paths.rs:7:31
  |
7 |     static S: fn() -> usize = bool::size;
  |                               ^^^^^^^^^^

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:538:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
             at librustc/util/common.rs:51
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:480
   6: std::panicking::begin_panic
             at /home/wesley/code/rust/rust/src/libstd/panicking.rs:410
   7: rustc_errors::Handler::span_bug
             at /home/wesley/code/rust/rust/src/<::std::macros::panic macros>:3
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
             at /home/wesley/code/rust/rust/src/librustc/util/bug.rs:45
   9: rustc::ty::context::tls::with_opt::{{closure}}
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2188
  10: rustc::ty::context::tls::with_context_opt
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2125
  11: rustc::ty::context::tls::with_opt
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2188
  12: rustc::util::bug::opt_span_bug_fmt
             at /home/wesley/code/rust/rust/src/librustc/util/bug.rs:42
  13: rustc::util::bug::span_bug_fmt
             at /home/wesley/code/rust/rust/src/librustc/util/bug.rs:33
  14: rustc_mir::const_eval::const_eval_raw_provider
             at librustc_mir/const_eval.rs:663
             at /home/wesley/code/rust/rust/src/libcore/result.rs:530
             at librustc_mir/const_eval.rs:646
  15: rustc::ty::query::__query_compute::const_eval_raw
             at librustc/ty/query/plumbing.rs:834
             at librustc/ty/query/plumbing.rs:796
  16: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::const_eval_raw<'tcx>>::compute
             at librustc/ty/query/plumbing.rs:826
  17: rustc::dep_graph::graph::DepGraph::with_task_impl
             at librustc/dep_graph/graph.rs:342
  18: rustc::ty::context::tls::with_related_context
             at librustc/dep_graph/graph.rs:208
             at librustc/ty/query/plumbing.rs:550
             at librustc/ty/query/plumbing.rs:208
             at librustc/ty/context.rs:2050
             at librustc/ty/context.rs:1989
             at librustc/ty/context.rs:2049
             at librustc/ty/query/plumbing.rs:207
             at librustc/ty/context.rs:2150
             at librustc/ty/context.rs:2134
             at librustc/ty/context.rs:2125
             at librustc/ty/context.rs:2134
             at librustc/ty/context.rs:2145
  19: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
             at librustc/ty/query/plumbing.rs:197
             at librustc/ty/query/plumbing.rs:543
  20: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
             at librustc/ty/query/plumbing.rs:383
             at librustc/ty/query/plumbing.rs:629
             at librustc/ty/query/plumbing.rs:640
  21: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::const_eval_raw
             at librustc/ty/query/plumbing.rs:888
             at librustc/ty/query/plumbing.rs:881
  22: rustc_mir::const_eval::const_eval_provider
             at librustc_mir/const_eval.rs:588
  23: rustc::ty::query::__query_compute::const_eval
             at librustc/ty/query/plumbing.rs:834
             at librustc/ty/query/plumbing.rs:796
  24: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::const_eval<'tcx>>::compute
             at librustc/ty/query/plumbing.rs:826
  25: rustc::dep_graph::graph::DepGraph::with_task_impl
             at librustc/dep_graph/graph.rs:342
  26: rustc::ty::context::tls::with_related_context
             at librustc/dep_graph/graph.rs:208
             at librustc/ty/query/plumbing.rs:550
             at librustc/ty/query/plumbing.rs:208
             at librustc/ty/context.rs:2050
             at librustc/ty/context.rs:1989
             at librustc/ty/context.rs:2049
             at librustc/ty/query/plumbing.rs:207
             at librustc/ty/context.rs:2150
             at librustc/ty/context.rs:2134
             at librustc/ty/context.rs:2125
             at librustc/ty/context.rs:2134
             at librustc/ty/context.rs:2145
  27: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
             at librustc/ty/query/plumbing.rs:197
             at librustc/ty/query/plumbing.rs:543
  28: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
             at librustc/ty/query/plumbing.rs:383
             at librustc/ty/query/plumbing.rs:629
             at librustc/ty/query/plumbing.rs:640
  29: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::const_eval
             at librustc/ty/query/plumbing.rs:888
             at librustc/ty/query/plumbing.rs:881
  30: rustc_mir::const_eval::const_eval_provider
             at librustc_mir/const_eval.rs:577
  31: rustc::ty::query::__query_compute::const_eval
             at librustc/ty/query/plumbing.rs:834
             at librustc/ty/query/plumbing.rs:796
  32: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::const_eval<'tcx>>::compute
             at librustc/ty/query/plumbing.rs:826
  33: rustc::dep_graph::graph::DepGraph::with_task_impl
             at librustc/dep_graph/graph.rs:342
  34: rustc::ty::context::tls::with_related_context
             at librustc/dep_graph/graph.rs:208
             at librustc/ty/query/plumbing.rs:550
             at librustc/ty/query/plumbing.rs:208
             at librustc/ty/context.rs:2050
             at librustc/ty/context.rs:1989
             at librustc/ty/context.rs:2049
             at librustc/ty/query/plumbing.rs:207
             at librustc/ty/context.rs:2150
             at librustc/ty/context.rs:2134
             at librustc/ty/context.rs:2125
             at librustc/ty/context.rs:2134
             at librustc/ty/context.rs:2145
  35: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
             at librustc/ty/query/plumbing.rs:197
             at librustc/ty/query/plumbing.rs:543
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
             at librustc/ty/query/plumbing.rs:383
             at librustc/ty/query/plumbing.rs:629
             at librustc/ty/query/plumbing.rs:640
  37: rustc::ty::query::<impl rustc::ty::context::TyCtxt<'a, 'tcx, 'lcx>>::const_eval
             at librustc/ty/query/plumbing.rs:888
             at librustc/ty/query/plumbing.rs:881
  38: rustc_lint::builtin::check_const
             at librustc_lint/builtin.rs:1288
  39: <rustc_lint::register_builtins::BuiltinCombinedLateLintPass as rustc::lint::LateLintPass<'a, 'tcx>>::check_item
             at librustc_lint/builtin.rs:0
             at /home/wesley/code/rust/rust/src/<::rustc::lint::expand_combined_late_lint_pass_methods macros>:11
  40: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
             at librustc/lint/context.rs:822
             at librustc/lint/context.rs:778
             at librustc/lint/context.rs:821
             at librustc/lint/context.rs:713
             at librustc/lint/context.rs:820
  41: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_block
             at librustc/hir/intravisit.rs:961
             at librustc/lint/context.rs:929
  42: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_expr
             at librustc/lint/context.rs:848
             at librustc/lint/context.rs:713
             at librustc/lint/context.rs:846
  43: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_body
             at librustc/hir/intravisit.rs:414
             at librustc/lint/context.rs:813
  44: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_nested_body
             at librustc/lint/context.rs:807
  45: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_fn
             at librustc/hir/intravisit.rs:842
             at librustc/lint/context.rs:871
  46: rustc::hir::intravisit::walk_item
             at librustc/hir/intravisit.rs:486
  47: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_item
             at librustc/lint/context.rs:823
             at librustc/lint/context.rs:778
             at librustc/lint/context.rs:821
             at librustc/lint/context.rs:713
             at librustc/lint/context.rs:820
  48: <rustc::lint::context::LateContext<'a, 'tcx> as rustc::hir::intravisit::Visitor<'tcx>>::visit_mod
             at librustc/hir/intravisit.rs:182
             at librustc/hir/intravisit.rs:405
             at librustc/lint/context.rs:916
  49: rustc::hir::intravisit::walk_crate
             at librustc/hir/intravisit.rs:391
  50: rustc::lint::context::check_crate
             at librustc/lint/context.rs:1214
             at librustc/lint/context.rs:713
             at librustc/lint/context.rs:1209
  51: rustc::util::common::time
             at librustc_driver/driver.rs:1353
             at /home/wesley/code/rust/rust/src/librustc/util/common.rs:163
             at /home/wesley/code/rust/rust/src/librustc/util/common.rs:157
  52: rustc::ty::context::tls::enter_context
             at librustc_driver/driver.rs:1353
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2082
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2050
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:1989
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2049
  53: <std::thread::local::LocalKey<T>>::with
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2081
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2039
             at /home/wesley/code/rust/rust/src/libstd/thread/local.rs:309
             at /home/wesley/code/rust/rust/src/libstd/thread/local.rs:255
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2031
             at /home/wesley/code/rust/rust/src/libstd/thread/local.rs:309
             at /home/wesley/code/rust/rust/src/libstd/thread/local.rs:255
  54: rustc::ty::context::TyCtxt::create_and_enter
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2023
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:2061
             at /home/wesley/code/rust/rust/src/librustc/ty/context.rs:1247
  55: rustc_driver::driver::compile_input
             at librustc_driver/driver.rs:1263
             at librustc_driver/driver.rs:287
  56: rustc_driver::run_compiler_with_pool
             at librustc_driver/lib.rs:552
  57: <scoped_tls::ScopedKey<T>>::set
             at librustc_driver/lib.rs:474
             at librustc_driver/driver.rs:76
             at /home/wesley/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  58: rustc_driver::run_compiler
             at librustc_driver/driver.rs:75
             at librustc_driver/lib.rs:473
  59: syntax::with_globals
             at librustc_driver/lib.rs:1725
             at librustc_driver/lib.rs:189
             at /home/wesley/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
             at /home/wesley/code/rust/rust/src/libsyntax/lib.rs:123
             at /home/wesley/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
             at /home/wesley/code/rust/rust/src/libsyntax/lib.rs:122
  60: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  61: std::panicking::try
             at /home/wesley/code/rust/rust/src/libstd/panicking.rs:289
  62: rustc_driver::run
             at /home/wesley/code/rust/rust/src/libstd/panic.rs:398
             at librustc_driver/lib.rs:1554
             at librustc_driver/lib.rs:1565
             at librustc_driver/lib.rs:1639
             at librustc_driver/lib.rs:187
  63: rustc_driver::main
             at librustc_driver/lib.rs:1718
  64: std::rt::lang_start::{{closure}}
             at /home/wesley/code/rust/rust/src/libstd/rt.rs:74
  65: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  66: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  67: std::panic::catch_unwind
             at libstd/panicking.rs:289
             at libstd/panic.rs:398
  68: std::rt::lang_start_internal
             at libstd/rt.rs:58
  69: main
  70: __libc_start_main
             at ../csu/libc-start.c:308
  71: _start
             at ../sysdeps/x86_64/start.S:120
query stack during panic:
#0 [const_eval_raw] const-evaluating `main::S`
#1 [const_eval] const-evaluating + checking `main::S`
#2 [const_eval] const-evaluating + checking `main::S`
end of query stack
error: aborting due to previous error
```

**Comment by wesleywiser** [comment]
## 11/14

Added more logging to try to pinpoint the divergence.

Commands to produce logs:

```
rustup override set stage2-3
RUST_LOG=rustc_mir,rustc::ty::instance rustc ufcs-polymorphic-paths.rs 2> working.mir.log
awk '{$1=$2=""; print $0}' working.mir.log > working.mir2.log

rustup override set stage1
RUST_LOG=rustc_mir,rustc::ty::instance rustc ufcs-polymorphic-paths.rs 2> broken.mir.log
awk '{$1=$2=""; print $0}' broken.mir.log > broken.mir2.log
```

**Comment by wesleywiser** [comment]
## 11/15

Adding more logging...

I may have a lead on the `TooGeneric` error I'm seeing in `ufcs-polymorphic-paths`.

**Comment by wesleywiser** [comment]
## 11/18

After an attempted fix:

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/debuginfo-lto.rs
    [run-pass] run-pass/fat-lto.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/lto-many-codegen-units.rs
    [run-pass] run-pass/lto-still-runs-thread-dtors.rs
    [run-pass] run-pass/optimization-fuel-0.rs
    [run-pass] run-pass/optimization-fuel-1.rs
    [run-pass] run-pass/panic-runtime/lto-abort.rs
    [run-pass] run-pass/panic-runtime/lto-unwind.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
    [run-pass] run-pass/sepcomp/sepcomp-lib-lto.rs
    [run-pass] run-pass/stack-probes-lto.rs
```

Seems to have fixed `ufcs-polymorphic-paths`.

Remaining failures (after removing bad lto tests and opt-fuel tests):

```
    [run-pass] run-pass/associated-consts/associated-const-cross-crate-defaults.rs
    [run-pass] run-pass/associated-consts/associated-const-use-default.rs
    [run-pass] run-pass/backtrace-debuginfo.rs
    [run-pass] run-pass/cross-crate/xcrate_generic_fn_nested_return.rs
    [run-pass] run-pass/generator/smoke.rs
    [run-pass] run-pass/issues/issue-11205.rs
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
```

**Comment by wesleywiser** [comment]
## 11/19

After another fix, the remaining failing test from the original set of changes I rebased on top of is:

```
    [run-pass] run-pass/rfcs/rfc-2005-default-binding-mode/constref.rs
```
